server:
  port: 8080
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
      name: testJob
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    hikari:
      maximum-pool-size: 5